### ISSUE TITLE
Add loading indicators

### ISSUE THREAD

**Issue by gabriel-flynn** [SHPE-UTDallas/ResumeBook#10]
Currently users aren't getting any feedback on components or pages that are loading and this is really needed on:
- Table component
    - When fetching table data add a loading indicator inside the Table body/content area
 - ~~AuthWrapper component~~
    - ~~On the initial load of our app we wait to render the actual application until we get back the users authentication status from the API~~
      - ~~Display a loading page while authentication status is being verified~~

The issue above was solved in #24

**Comment by chris-cybula** [comment]
Happy to help with this one. Still valid?

**Comment by gabriel-flynn** [comment]
@chris-cybula Yes it's still valid, that would be a huge help if you're still interested! If you want to knock this one out let me know and I'll assign it to you

**Comment by chris-cybula** [comment]
Yes, I would like to. Please assign it to me. Thanks

**Comment by gabriel-flynn** [comment]
@chris-cybula I have some information on how to setup your dev environment in the readme on the dev branch. For this issue you could probably get away without setting up the backend so you can ignore all the netlify stuff if you're not interested in setting that up (although you might have to comment out or mock a few API calls) . I'd recommend starting on the AuthWrapper component (src/AuthWrapper.js) since that one is pretty straightforward, you would just need to add the loading page/what you want to be rendered in the else branch. 

A possible idea would be to just render `<NavBar>
      <YourLoadingComponentHere />
</Navbar>` in the else branch but feel free to take it your own direction

I'll look into refactoring the Table component so that it's easy to tell when an API call is in progress and make it more straightforward to add a loading indicator/circle/something to the actual table body

If you have any questions or need any help setting up your dev environment just let me know, I appreciate the help!

**Comment by gabriel-flynn** [comment]
I refactored the Table component a bit in #20 and it's now live on the dev branch. If you look at the tableBody function in the Table component you would just need to replace the line that says `<h1>Loading...</h1>` with your implementation

**Comment by chris-cybula** [comment]
Thank you @gabriel-flynn for all the details. I really appreciate that! I will keep you updated.

**Comment by chris-cybula** [comment]
Can you provide environment variables please?

**Comment by gabriel-flynn** [comment]
@chris-cybula I updated the dev branch to no longer call the status endpoint and instead store the user's current authentication status in localStorage. I just tested it without any environment variables (I just ran `netlify dev`) and I'm able to load the /demo page fine so that should hopefully fix the issue you were having (since calling the /auth/status was probably causing errors). 

This change eliminates the need to add a loading page for the AuthWrapper component. I'm really sorry if you started working on that already, I'm not sure why I didn't use localStorage in the first place but it suddenly occurred to me that that would be a much better option.

If you run the application and click on the demos button (/demo) you can view the Table with fake data so that should be all you need to implement the loading feature for the table. I would recommend changing `line 31` in Table.js to `this.setState({ loading: true })` or just commenting out the componentDidMount() function all together so that it's always 'loading' and way easier to see the loading indicator/circle/what you decide to implement rendered in the table.

**All of the below is only if you're interested in getting the application 100% functional and is not needed to implement this fix:**
If you're still interested in getting the application running on your machine I would take a look at src/functions/utils/config.js as that is where most of the environment variables I use are listed at. You would need to go to https://www.linkedin.com/developers/ to create an app then save the clientid as LINKEDIN_CLIENT_ID on netlify, and do the same thing for the secret. Then for firebase you would need to create a Firebase Cloud Firestore database and follow the instructions here to get your private key: https://firebase.google.com/docs/admin/setup#initialize-sdk and then paste the JSON private key/info that is generated into netlify and save it as FIREBASE.

For setting up the resumes collection on firestore I would recommend adding that manually as we have a form to upload them (located at /upload) but getting cloudinary to allow you to embed pdfs on a free account can take a bit. (If you were able to do that you could set CLOUDINARY_URL in netlify  (It looks something like cloudinary://bunchOfNumbers:Key@cloudinaryProject/OrganizationName )

**Comment by chris-cybula** [comment]
Ok, I will start working on the task in itself. The only problem I have is that I can't get data on my local machine.

**Comment by gabriel-flynn** [comment]
@chris-cybula were you able to get the `netlify dev` command working/running? (The steps to set it up should be in the readme). As long as you don't try to login and just click on the 'Demo' button when initially loading the web app you should still be able to see data in your local environment even without environment variables as that route has no reliance on a database, login, etc. 

If you are running into any issues with setting up the netlify CLI tool just let me know and I'd be happy to help!

**Comment by gabriel-flynn** [comment]
@chris-cybula Actually I think you'll have to create a `.env` file in the root directory of the project and inside it set `NODE_ENV=development` as that does help set a few other environment variables that could give you trouble if they're properly defined

**Comment by chris-cybula** [comment]
That was it! Everything works fine now.

This is what I've got so far. I will try to use Material-UI to be consistent.
![image](https://user-images.githubusercontent.com/28848115/86135204-664e3c80-bae2-11ea-9fb1-4524ae824fdd.png)

**Comment by gabriel-flynn** [comment]
@chris-cybula That looks awesome! That's way better than what I would have done, the only change I would possibly make is maybe make it blue to fit with the color of the filter toggles. I definitely don't have an eye for design/theming (If you can't tell by the current UI hahaha) so if you want to keep it green or change it to a color other than blue feel free to do so!
